import React, { ReactNode, useState, useEffect } from "react";
import { Download, Share2, Check, Copy, Calendar, X, AlertCircle, RefreshCw, BadgeAlert, Ticket } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { TeamAvatar } from "@/cricket/components/TeamAvatar";
import { VsBadge } from "@/cricket/components/VsBadge";
import { ShieldCheck } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";
import { api } from "@/lib/api";
import { useAuth } from "@/hooks/use-auth";
import { BookingTicket } from "@/booking/BookingTicket";
import { useBookingTicket } from "@/hooks/useBookingTicket";
import playTurfLogo from "../assets/play-turf-logo.png";

interface BookingSuccessReceiptProps {
    turf: any;
    booking: any;
    cricket: any;
    total: number;
    placedAt: Date;
    navigate: (path: string) => void;
}

function ReceiptPanel({ title, children }: { title: string; children: ReactNode }) {
    return (
        <div
            className="rounded-[2rem] border p-4.5 transition-all duration-300"
            style={{ backgroundColor: "var(--bg-secondary)", borderColor: "var(--border-primary)" }}
        >
            <p className="mb-3.5 text-[9px] font-extrabold uppercase tracking-widest text-primary">{title}</p>
            <div className="space-y-2">{children}</div>
        </div>
    );
}

function ReceiptRow({ label, value, strong, success }: { label: string; value: string; strong?: boolean; success?: boolean }) {
    return (
        <div className="flex items-start justify-between gap-3 border-b border-border/10 pb-2 text-xs last:border-b-0 last:pb-0" style={{ borderBottomColor: "var(--border-primary)" }}>
            <span className="text-muted-foreground font-semibold">{label}</span>
            <span
                className={cn("max-w-[58%] text-right font-black font-display")}
                style={{
                    color: strong
                        ? "var(--gold-primary)"
                        : success
                            ? "var(--emerald-primary)"
                            : "var(--text-primary)"
                }}
            >
                {value}
            </span>
        </div>
    );
}

function ReceiptButton({ label, icon: Icon, onClick, primary }: { label: string; icon?: LucideIcon; onClick: () => void; primary?: boolean }) {
    return (
        <button
            onClick={onClick}
            className={cn(
                "pressable inline-flex items-center justify-center gap-2 rounded-2xl px-4 py-3 text-xs font-black uppercase tracking-wider transition cursor-pointer border-none flex-1",
                primary
                    ? "bg-gradient-neon text-primary-foreground shadow-neon"
                    : "border border-border bg-panel text-foreground"
            )}
            style={{
                borderColor: primary ? "none" : "var(--border-primary)",
                backgroundColor: primary ? "none" : "var(--card-bg)"
            }}
        >
            {Icon ? <Icon className="h-4 w-4" /> : null}
            {label}
        </button>
    );
}

const formatSlotTime = (timeStr: string) => {
    const [hourStr, minStr] = timeStr.split(":");
    let hour = parseInt(hourStr, 10);
    const ampm = hour >= 12 ? "PM" : "AM";
    hour = hour % 12;
    if (hour === 0) hour = 12;
    const formattedHour = hour.toString().padStart(2, "0");
    return `${formattedHour}:${minStr} ${ampm}`;
};

function receiptText(booking: any, cricket: any, turf: any, total: number) {
    const totalPaid = (total * 1.18) + 20;
    return [
        "PLAY_TURF Payment Receipt",
        "Your Match. Your Turf. Your Victory.",
        `Booking ID: ${booking.id}`,
        `Turf: ${turf.name}`,
        `Match: ${cricket.teamA?.name} vs ${cricket.teamB?.name}`,
        `Booking Date: ${booking.date}`,
        `Start Time: ${formatSlotTime(booking.start_time)}`,
        `Transaction ID: ${booking.payment_id || "TXN-PENDING"}`,
        `Base Turf Cost: Rs ${total}`,
        "Platform Fee: Rs 20",
        `GST (18%): Rs ${(total * 0.18).toLocaleString()}`,
        `Total Paid: Rs ${totalPaid.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        `Payment Method: ${cricket.state.paymentMethod || "UPI"}`,
        "Payment Status: SUCCESS",
        "This receipt is digitally generated by PlayTurf.",
    ].join("\n");
}

function downloadReceipt(booking: any, cricket: any, turf: any, total: number) {
    const blob = new Blob([receiptText(booking, cricket, turf, total)], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${booking.id}-receipt.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
}

async function shareReceipt(booking: any, cricket: any, turf: any, total: number) {
    const text = receiptText(booking, cricket, turf, total);
    if (navigator.share) {
        await navigator.share({ title: "PlayTurf Booking Confirmed", text });
    } else {
        await navigator.clipboard.writeText(text);
        toast.success("Receipt copied to clipboard");
    }
}

export function BookingSuccessReceipt({
    turf,
    booking,
    cricket,
    total,
    placedAt,
    navigate
}: BookingSuccessReceiptProps) {
    const [verificationState, setVerificationState] = useState<"verifying" | "confirmed" | "cancelled" | "failed">("verifying");
    const [currentVerifyStep, setCurrentVerifyStep] = useState(0);
    const [countdownSeconds, setCountdownSeconds] = useState(900); // 15 mins
    const [isCancelling, setIsCancelling] = useState(false);
    const [showTicket, setShowTicket] = useState(false);
    const { user } = useAuth();
    const { ticketRef, downloadPDF, shareTicket, isGenerating } = useBookingTicket();

    // Compute duration & slot hours
    const durationHours = Math.max(1, Math.round(total / turf.price_per_hour));
    const [sh, sm] = booking.start_time.split(":").map(Number);
    const eh = sh + durationHours;
    const end_time_str = `${eh.toString().padStart(2, "0")}:${sm.toString().padStart(2, "0")}`;

    const releasedSlots = [];
    for (let i = 0; i < durationHours; i++) {
        const slotHour = (sh + i).toString().padStart(2, "0");
        releasedSlots.push(formatSlotTime(`${slotHour}:${sm.toString().padStart(2, "0")}`));
    }

    // Step-by-step verification progress simulator
    const verificationSteps = [
        "Payment successfully received",
        "Payment amount matches booking amount",
        "Transaction ID is valid",
        "All requested slots are still available",
        "Slot reservation saved in database"
    ];

    useEffect(() => {
        if (verificationState === "verifying") {
            const interval = setInterval(() => {
                setCurrentVerifyStep((prev) => {
                    if (prev >= verificationSteps.length - 1) {
                        clearInterval(interval);
                        setTimeout(() => {
                            setVerificationState("confirmed");
                        }, 500);
                        return prev;
                    }
                    return prev + 1;
                });
            }, 600);
            return () => clearInterval(interval);
        }
    }, [verificationState]);

    // Live countdown timer handler
    useEffect(() => {
        if (verificationState === "confirmed") {
            // Recalculate remaining seconds based on database created_at
            const calculateRemaining = () => {
                const createdTime = new Date(booking.created_at).getTime();
                const elapsedMs = Date.now() - createdTime;
                const remainingMs = (15 * 60 * 1000) - elapsedMs;
                return Math.max(0, Math.floor(remainingMs / 1000));
            };

            setCountdownSeconds(calculateRemaining());

            const timer = setInterval(() => {
                const rem = calculateRemaining();
                setCountdownSeconds(rem);
                if (rem <= 0) {
                    clearInterval(timer);
                }
            }, 1000);

            return () => clearInterval(timer);
        }
    }, [verificationState, booking.created_at]);

    // Handle cancellation
    const handleCancelBooking = async () => {
        setIsCancelling(true);
        try {
            await api.cancelBooking(booking.id);
            setVerificationState("cancelled");
            toast.success("Booking cancelled & refund initiated!");
        } catch (error) {
            toast.error((error as Error).message || "Failed to cancel booking");
        } finally {
            setIsCancelling(false);
        }
    };

    // Copy Booking ID
    const handleCopyId = () => {
        navigator.clipboard.writeText(booking.id);
        toast.success("Booking ID copied!");
    };

    // Google Calendar Link generator
    const getGoogleCalendarUrl = () => {
        const title = encodeURIComponent(`PlayTurf Booking: ${turf.name}`);
        const details = encodeURIComponent(`Booking ID: ${booking.id}\nDuration: ${durationHours} Hour(s)\nAddress: ${turf.city}, India`);
        const cleanDate = booking.date.replace(/-/g, "");
        const startHour = sh.toString().padStart(2, "0");
        const endHour = eh.toString().padStart(2, "0");
        const minStr = sm.toString().padStart(2, "0");
        const dates = `${cleanDate}T${startHour}${minStr}00/${cleanDate}T${endHour}${minStr}00`;
        return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${dates}&details=${details}&location=${encodeURIComponent(turf.city)}`;
    };

    const formatCountdown = (secs: number) => {
        const mins = Math.floor(secs / 60);
        const remainingSecs = secs % 60;
        return `${mins.toString().padStart(2, "0")}:${remainingSecs.toString().padStart(2, "0")}`;
    };

    const getCancellationEndTime = () => {
        const createdTime = new Date(booking.created_at);
        const endTime = new Date(createdTime.getTime() + 15 * 60 * 1000);
        return endTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    };

    return (
        <motion.div key="success" initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} className="relative px-4 pb-36 pt-5 text-center">

            {/* Confetti Animation (Only on confirmed state) */}
            {verificationState === "confirmed" && (
                <div className="pointer-events-none fixed inset-0 overflow-hidden z-40">
                    {Array.from({ length: 24 }).map((_, index) => (
                        <span
                            key={index}
                            className="animate-confetti absolute h-2.5 w-2.5 rounded-full"
                            style={{
                                left: `${(index * 37) % 100}%`,
                                animationDelay: `${(index % 8) * 0.15}s`,
                                backgroundColor: index % 3 === 0
                                    ? "var(--l-gold)"
                                    : index % 3 === 1
                                        ? "var(--l-emerald)"
                                        : "var(--primary)",
                            }}
                        />
                    ))}
                </div>
            )}

            <div
                className="mx-auto max-w-3xl overflow-hidden rounded-[2rem] border text-left shadow-2xl transition-all duration-300"
                style={{
                    backgroundColor: "var(--card-bg)",
                    borderColor: "var(--border-primary)",
                    boxShadow: "var(--shadow-primary)",
                }}
            >
                <AnimatePresence mode="wait">
                    {/* STATE 1: PROCESSING / VERIFYING */}
                    {verificationState === "verifying" && (
                        <motion.div
                            key="verifying-view"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0 }}
                            className="p-8 text-center"
                        >
                            <div className="relative flex justify-center mb-6">
                                <RefreshCw className="h-16 w-16 text-primary animate-spin" />
                            </div>
                            <h2 className="text-xl font-black font-display text-foreground">
                                Verifying Payment & Reserving Your Slot...
                            </h2>
                            <p className="mt-2 text-xs text-muted-foreground font-semibold">
                                Please wait while we finalize your booking secure pipeline.
                            </p>

                            <div className="mt-8 max-w-md mx-auto space-y-3.5 text-left border border-[var(--border-primary)] p-5 rounded-2xl bg-[var(--bg-secondary)]">
                                {verificationSteps.map((stepName, idx) => (
                                    <div key={idx} className="flex items-center gap-3.5">
                                        <div className={cn(
                                            "h-5 w-5 rounded-full flex items-center justify-center border text-[10px] font-bold transition-all duration-300",
                                            currentVerifyStep > idx
                                                ? "bg-[var(--emerald-primary)] border-transparent text-black"
                                                : currentVerifyStep === idx
                                                    ? "border-primary text-primary animate-pulse"
                                                    : "border-muted text-muted-foreground"
                                        )}>
                                            {currentVerifyStep > idx ? <Check className="h-3.5 w-3.5 stroke-[3]" /> : idx + 1}
                                        </div>
                                        <span className={cn(
                                            "text-xs font-semibold tracking-wide",
                                            currentVerifyStep > idx
                                                ? "text-[var(--emerald-primary)]"
                                                : currentVerifyStep === idx
                                                    ? "text-primary font-bold"
                                                    : "text-muted-foreground"
                                        )}>
                                            {stepName}
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </motion.div>
                    )}

                    {/* STATE 2: CONFIRMED */}
                    {verificationState === "confirmed" && (
                        <motion.div
                            key="confirmed-view"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0 }}
                        >
                            {/* Receipt Header Banner */}
                            <div className="relative overflow-hidden border-b p-6 text-center" style={{ borderBottomColor: "var(--border-primary)" }}>
                                <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_50%_0%,var(--primary),transparent_50%)]" />
                                <div className="absolute inset-x-10 top-0 h-[2px] bg-gradient-neon" />
                                <div className="relative flex flex-col items-center">
                                    <img src={playTurfLogo} alt="Play Turf Logo" className="w-12 h-12 object-contain mb-2.5" />
                                    <p className="text-[10px] font-black uppercase tracking-[0.32em] text-primary">PLAYTURF CONFIRMATION</p>
                                    <h2 className="mt-1 font-display text-2xl font-black text-foreground">Booking Confirmed</h2>
                                    <p className="mt-2 text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Your Match. Your Turf. Your Victory.</p>
                                </div>
                            </div>

                            <div className="p-5 sm:p-7">
                                <motion.div
                                    initial={{ scale: 0 }}
                                    animate={{ scale: 1 }}
                                    transition={{ type: "spring", stiffness: 220 }}
                                    className="mx-auto grid h-16 w-16 place-items-center rounded-full border transition-all duration-300"
                                    style={{
                                        borderColor: "var(--border-primary)",
                                        backgroundColor: "var(--l-accent-soft)",
                                        boxShadow: "var(--l-shadow-glow)"
                                    }}
                                >
                                    <Check className="h-8 w-8 text-primary" strokeWidth={3} />
                                </motion.div>
                                <div className="mt-4 text-center">
                                    <div className="inline-flex items-center gap-1.5 rounded-full px-3 py-1 bg-[var(--l-accent-soft)] border border-[var(--border-primary)] text-xs text-primary font-black uppercase tracking-wider">
                                        <ShieldCheck className="h-4 w-4" /> Booked
                                    </div>
                                    <p className="mt-2 text-xs text-muted-foreground font-semibold">Your slots are securely locked in the database.</p>
                                </div>

                                {/* Free Cancellation Countdown Section */}
                                <div className="mt-6 border border-[var(--border-primary)] bg-[var(--bg-secondary)] rounded-2xl p-4.5 text-center relative overflow-hidden">
                                    {countdownSeconds > 0 ? (
                                        <>
                                            <p className="text-[9px] font-extrabold uppercase tracking-widest text-[var(--gold-primary)]">Free Cancellation Available For</p>
                                            <div className="mt-2 font-display text-3xl font-black tracking-widest text-[var(--gold-primary)] animate-pulse">
                                                {formatCountdown(countdownSeconds)}
                                            </div>
                                            <p className="mt-1.5 text-[10px] text-muted-foreground font-semibold">
                                                Countdown End: <span className="text-foreground font-bold">{getCancellationEndTime()}</span>
                                            </p>
                                            <button
                                                onClick={handleCancelBooking}
                                                disabled={isCancelling}
                                                className="mt-4 w-full pressable inline-flex items-center justify-center gap-2 rounded-xl bg-red-950/40 border border-red-500/30 text-red-400 py-3 text-xs font-black uppercase tracking-wider transition hover:bg-red-900/50 cursor-pointer disabled:opacity-50"
                                            >
                                                {isCancelling ? "Cancelling..." : "Cancel Booking"}
                                            </button>
                                        </>
                                    ) : (
                                        <>
                                            <div className="inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 bg-zinc-800/60 border border-zinc-700 text-[10px] text-zinc-400 font-extrabold uppercase tracking-wider">
                                                Free cancellation period has ended. No refund available.
                                            </div>
                                        </>
                                    )}
                                </div>

                                <div
                                    className="mt-6 rounded-3xl border p-4 transition-all duration-300"
                                    style={{ backgroundColor: "var(--bg-secondary)", borderColor: "var(--border-primary)" }}
                                >
                                    <p className="mb-4 text-[9px] font-extrabold uppercase tracking-widest text-primary">Team Roster Showcase</p>
                                    <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center">
                                        <TeamAvatar team={cricket.teamA} size="lg" className="mx-auto border border-border/40 shadow-sm transition hover:scale-105" />
                                        <VsBadge />
                                        <TeamAvatar team={cricket.teamB} size="lg" className="mx-auto border border-border/40 shadow-sm transition hover:scale-105" />
                                        <p className="truncate text-sm font-black text-foreground font-display">{cricket.teamA?.name}</p>
                                        <span />
                                        <p className="truncate text-sm font-black text-foreground font-display">{cricket.teamB?.name}</p>
                                    </div>
                                </div>

                                <div className="mt-5 grid gap-4 md:grid-cols-2">
                                    <ReceiptPanel title="Booking Details">
                                        <div className="flex items-center justify-between border-b border-border/10 pb-2 text-xs">
                                            <span className="text-muted-foreground font-semibold">Booking ID</span>
                                            <div className="flex items-center gap-1.5">
                                                <span className="font-black text-foreground font-display">{booking.id}</span>
                                                <button onClick={handleCopyId} className="p-1 hover:bg-white/10 rounded text-muted-foreground hover:text-foreground cursor-pointer">
                                                    <Copy className="h-3.5 w-3.5" />
                                                </button>
                                            </div>
                                        </div>
                                        <ReceiptRow label="Turf Name" value={turf.name} />
                                        <ReceiptRow label="Date" value={booking.date} />
                                        <ReceiptRow label="Start Time" value={formatSlotTime(booking.start_time)} />
                                        <ReceiptRow label="End Time" value={formatSlotTime(end_time_str)} />
                                        <ReceiptRow label="Duration" value={`${durationHours} Hour(s)`} />
                                        <ReceiptRow label="Amount Paid" value={`₹${total.toLocaleString()}`} strong />
                                        <ReceiptRow label="Payment ID" value={booking.payment_id || "TXN-PENDING"} />
                                        <ReceiptRow label="Booking Status" value="Booked" success />
                                    </ReceiptPanel>

                                    <ReceiptPanel title="Billing Details">
                                        <ReceiptRow label="Base Fee" value={`Rs ${total.toLocaleString()}`} />
                                        <ReceiptRow label="Platform Charge" value="Rs 20" />
                                        <ReceiptRow label="Sports GST (18%)" value={`Rs ${(total * 0.18).toLocaleString()}`} />
                                        <ReceiptRow label="Grand Total" value={`Rs ${(total * 1.18 + 20).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`} strong />
                                        <ReceiptRow label="Billing method" value={cricket.state.paymentMethod || "UPI"} />
                                        <ReceiptRow label="Ledger Status" value="SUCCESS" success />
                                    </ReceiptPanel>
                                </div>

                                <div className="mt-6 flex flex-col sm:flex-row gap-3">
                                    <ReceiptButton onClick={() => setShowTicket(true)} label="View Premium Ticket" icon={Ticket} primary />
                                    <ReceiptButton onClick={() => shareTicket({
                                        bookingId: booking.id,
                                        turfName: turf.name,
                                        sport: turf.sport_types?.[0] || "Football",
                                        date: booking.date,
                                        startTime: booking.start_time,
                                        endTime: end_time_str,
                                        duration: durationHours,
                                        amount: total,
                                        status: booking.status,
                                        paymentId: booking.payment_id,
                                        playerName: user?.name || "Player",
                                        address: turf.address,
                                        paymentMethod: cricket.state?.paymentMethod || "UPI",
                                        bookedAt: booking.created_at,
                                    })} label="Share Booking" icon={Share2} />
                                    <a
                                        href={getGoogleCalendarUrl()}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="pressable inline-flex items-center justify-center gap-2 rounded-2xl px-4 py-3 text-xs font-black uppercase tracking-wider transition cursor-pointer border border-border bg-panel text-foreground flex-1 text-center"
                                        style={{ borderColor: "var(--border-primary)", backgroundColor: "var(--card-bg)" }}
                                    >
                                        <Calendar className="h-4 w-4 text-primary" />
                                        Add to Calendar
                                    </a>
                                </div>

                                <footer className="mt-7 border-t border-[var(--border-primary)] pt-4 text-center">
                                    <p className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider">© 2026 PlayTurf — All Rights Reserved</p>
                                    <div className="mt-2 flex flex-wrap justify-center gap-3 text-[9px] text-muted-foreground uppercase font-black tracking-wider">
                                        <span>Terms</span>
                                        <span>Privacy</span>
                                        <span>concierge support</span>
                                    </div>
                                </footer>
                            </div>
                        </motion.div>
                    )}

                    {/* STATE 3: REFUND / CANCELLED */}
                    {verificationState === "cancelled" && (
                        <motion.div
                            key="cancelled-view"
                            initial={{ opacity: 0, scale: 0.95 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0 }}
                            className="p-6 sm:p-8 text-center"
                        >
                            <div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-red-950/40 border border-red-500/40 mb-5">
                                <X className="h-8 w-8 text-red-500" strokeWidth={3} />
                            </div>

                            <h1 className="font-display text-2xl font-black text-foreground">Booking Cancelled Successfully</h1>
                            <p className="mt-2 text-xs text-muted-foreground font-semibold">Your slots have been released and the refund pipeline has been initiated.</p>

                            <div className="mt-6 space-y-4 max-w-md mx-auto text-left border border-[var(--border-primary)] p-5 rounded-2xl bg-[var(--bg-secondary)]">
                                <p className="text-[10px] font-extrabold uppercase tracking-widest text-primary border-b border-border/10 pb-2 mb-3">Refund Tracking Status</p>
                                
                                <div className="flex justify-between items-center text-xs pb-2 border-b border-border/10">
                                    <span className="text-muted-foreground font-semibold">Refund Status</span>
                                    <span className="font-black text-[var(--gold-primary)] font-display uppercase tracking-wider">Initiated</span>
                                </div>
                                <div className="flex justify-between items-center text-xs pb-2 border-b border-border/10">
                                    <span className="text-muted-foreground font-semibold">Refund Amount</span>
                                    <span className="font-black text-foreground font-display">₹{total.toLocaleString()}</span>
                                </div>
                                <div className="flex justify-between items-center text-xs pb-2 border-b border-border/10">
                                    <span className="text-muted-foreground font-semibold">Expected Refund Time</span>
                                    <span className="font-black text-foreground font-display">3-7 Business Days</span>
                                </div>
                                <div className="text-xs pt-1">
                                    <span className="text-muted-foreground font-semibold block mb-2">Released Slots:</span>
                                    <ul className="grid grid-cols-2 gap-2">
                                        {releasedSlots.map((slotTime, idx) => (
                                            <li key={idx} className="flex items-center gap-1.5 bg-white/5 border border-white/10 px-2.5 py-1 rounded-lg text-[10px] font-bold text-foreground font-display">
                                                <div className="w-1.5 h-1.5 rounded-full bg-[var(--emerald-primary)]" />
                                                {slotTime}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </div>

                            <button
                                onClick={() => navigate("/")}
                                className="mt-8 px-8 py-3.5 rounded-xl bg-gradient-neon text-primary-foreground font-black text-xs uppercase tracking-wider shadow-neon border-none cursor-pointer"
                            >
                                Return to Home
                            </button>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

            {verificationState === "confirmed" && (
                <div
                    className="sticky bottom-0 mx-4 mb-4 z-50 rounded-[24px] border bg-panel-3/95 p-3.5 shadow-2xl backdrop-blur-xl sm:hidden"
                    style={{ borderColor: "var(--border-primary)" }}
                >
                    <div className="mx-auto grid grid-cols-4 gap-2.5">
                        <button onClick={() => setShowTicket(true)} className="pressable rounded-xl bg-gradient-neon text-primary-foreground font-black text-[9px] uppercase py-2.5 shadow-neon">Ticket</button>
                        <button onClick={() => shareTicket({
                            bookingId: booking.id,
                            turfName: turf.name,
                            sport: turf.sport_types?.[0] || "Football",
                            date: booking.date,
                            startTime: booking.start_time,
                            endTime: end_time_str,
                            duration: durationHours,
                            amount: total,
                            status: booking.status,
                            paymentId: booking.payment_id,
                            playerName: user?.name || "Player",
                            address: turf.address,
                            paymentMethod: cricket.state?.paymentMethod || "UPI",
                            bookedAt: booking.created_at,
                        })} className="pressable rounded-xl border border-border bg-panel text-foreground font-black text-[9px] uppercase py-2.5" style={{ borderColor: "var(--border-primary)" }}>Share</button>
                        <button onClick={() => navigate("/")} className="pressable rounded-xl border border-border bg-panel text-foreground font-black text-[9px] uppercase py-2.5" style={{ borderColor: "var(--border-primary)" }}>Home</button>
                        <button onClick={() => navigate(`/booking/new/${turf.id}`)} className="pressable rounded-xl bg-gradient-neon text-primary-foreground font-black text-[9px] uppercase py-2.5 shadow-neon">Book New</button>
                    </div>
                </div>
            )}
            {showTicket && (
                <AnimatePresence>
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 z-50 bg-black/90 backdrop-blur-md overflow-y-auto p-4"
                    >
                        <div className="max-w-lg mx-auto">
                            <div className="flex items-center justify-between mb-4 sticky top-0 z-10 py-2">
                                <h3 className="text-lg font-bold text-white">Your Booking Ticket</h3>
                                <button
                                    onClick={() => setShowTicket(false)}
                                    className="p-2 rounded-full bg-white/10 hover:bg-white/20 transition cursor-pointer border-none"
                                >
                                    <X className="w-5 h-5 text-white" />
                                </button>
                            </div>
                            <BookingTicket
                                ref={ticketRef}
                                booking={booking}
                                turf={turf}
                                user={user ? { name: user.name, email: user.email } : undefined}
                                onDownload={() => {
                                    if (ticketRef.current) {
                                        downloadPDF(ticketRef.current, `PlayTurf-Booking-${booking.id}`);
                                    }
                                }}
                                onShare={() => shareTicket({
                                    bookingId: booking.id,
                                    turfName: turf.name,
                                    sport: turf.sport_types?.[0] || "Football",
                                    date: booking.date,
                                    startTime: booking.start_time,
                                    endTime: end_time_str,
                                    duration: durationHours,
                                    amount: total,
                                    status: booking.status,
                                    paymentId: booking.payment_id,
                                    playerName: user?.name || "Player",
                                    address: turf.address,
                                    paymentMethod: cricket.state?.paymentMethod || "UPI",
                                    bookedAt: booking.created_at,
                                })}
                                isGenerating={isGenerating}
                            />
                        </div>
                    </motion.div>
                </AnimatePresence>
            )}
        </motion.div>
    );
}
