import React, { ReactNode } from "react";
import { Download, Share2, Check } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { TeamAvatar } from "@/cricket/components/TeamAvatar";
import { VsBadge } from "@/cricket/components/VsBadge";
import { ShieldCheck } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { motion } from "framer-motion";

interface BookingSuccessReceiptProps {
    turf: any;
    booking: any;
    cricket: any;
    total: number;
    placedAt: Date;
    navigate: (path: string) => void;
}

function ReceiptPanel({ title, children }: { title: string; children: ReactNode }) {
    return (
        <div
            className="rounded-[2rem] border p-4.5 transition-all duration-300"
            style={{ backgroundColor: "var(--bg-secondary)", borderColor: "var(--border-primary)" }}
        >
            <p className="mb-3.5 text-[9px] font-extrabold uppercase tracking-widest text-primary">{title}</p>
            <div className="space-y-2">{children}</div>
        </div>
    );
}

function ReceiptRow({ label, value, strong, success }: { label: string; value: string; strong?: boolean; success?: boolean }) {
    return (
        <div className="flex items-start justify-between gap-3 border-b border-border/10 pb-2 text-xs last:border-b-0 last:pb-0" style={{ borderBottomColor: "var(--border-primary)" }}>
            <span className="text-muted-foreground font-semibold">{label}</span>
            <span
                className={cn("max-w-[58%] text-right font-black font-display")}
                style={{
                    color: strong
                        ? "var(--gold-primary)"
                        : success
                            ? "var(--emerald-primary)"
                            : "var(--text-primary)"
                }}
            >
                {value}
            </span>
        </div>
    );
}

function ReceiptButton({ label, icon: Icon, onClick, primary }: { label: string; icon?: LucideIcon; onClick: () => void; primary?: boolean }) {
    return (
        <button
            onClick={onClick}
            className={cn(
                "pressable inline-flex items-center justify-center gap-2 rounded-2xl px-4 py-3 text-xs font-black uppercase tracking-wider transition cursor-pointer border-none",
                primary
                    ? "bg-gradient-neon text-primary-foreground shadow-neon"
                    : "border border-border bg-panel text-foreground"
            )}
            style={{
                borderColor: primary ? "none" : "var(--border-primary)",
                backgroundColor: primary ? "none" : "var(--card-bg)"
            }}
        >
            {Icon ? <Icon className="h-4 w-4" /> : null}
            {label}
        </button>
    );
}

function receiptText(booking: any, cricket: any) {
    const totalPaid = (booking.amount * 1.18) + 20;
    return [
        "PLAY_TURF Payment Receipt",
        "Your Match. Your Turf. Your Victory.",
        `Turf Booking: ${booking.id}`,
        `Turf: ${booking.turf_name}`,
        `Match: ${cricket.teamA?.name} vs ${cricket.teamB?.name}`,
        `Booking ID: ${cricket.state.bookingId}`,
        `Transaction ID: ${booking.payment_id || "TXN-PENDING"}`,
        `Base Turf Cost: Rs ${booking.amount}`,
        "Platform Fee: Rs 20",
        `GST (18%): Rs ${(booking.amount * 0.18).toLocaleString()}`,
        `Total Paid: Rs ${totalPaid.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        `Payment Method: ${cricket.state.paymentMethod}`,
        "Payment Status: SUCCESS",
        "This receipt is digitally generated by PlayTurf.",
    ].join("\n");
}

function downloadReceipt(booking: any, cricket: any) {
    const blob = new Blob([receiptText(booking, cricket)], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${booking.id}-receipt.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
}

async function shareReceipt(booking: any, cricket: any) {
    const text = receiptText(booking, cricket);
    if (navigator.share) {
        await navigator.share({ title: "PlayTurf Booking Confirmed", text });
    } else {
        await navigator.clipboard.writeText(text);
        toast.success("Receipt copied");
    }
}

export function BookingSuccessReceipt({
    turf,
    booking,
    cricket,
    total,
    placedAt,
    navigate
}: BookingSuccessReceiptProps) {
    return (
        <motion.div key="success" initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} className="relative px-4 pb-36 pt-5 text-center">

            {/* Confetti Animation */}
            <div className="pointer-events-none fixed inset-0 overflow-hidden z-40">
                {Array.from({ length: 24 }).map((_, index) => (
                    <span
                        key={index}
                        className="animate-confetti absolute h-2.5 w-2.5 rounded-full"
                        style={{
                            left: `${(index * 37) % 100}%`,
                            animationDelay: `${(index % 8) * 0.15}s`,
                            backgroundColor: index % 3 === 0
                                ? "var(--l-gold)"
                                : index % 3 === 1
                                    ? "var(--l-emerald)"
                                    : "var(--primary)",
                        }}
                    />
                ))}
                {Array.from({ length: 18 }).map((_, index) => (
                    <span
                        key={`particle-${index}`}
                        className="absolute h-1.5 w-1.5 animate-float rounded-full opacity-60 shadow-sm"
                        style={{
                            left: `${(index * 19) % 100}%`,
                            top: `${12 + ((index * 23) % 72)}%`,
                            animationDelay: `${index * 0.12}s`,
                            backgroundColor: "var(--primary)"
                        }}
                    />
                ))}
            </div>

            <div
                className="mx-auto max-w-3xl overflow-hidden rounded-[2rem] border text-left shadow-2xl transition-all duration-300"
                style={{
                    backgroundColor: "var(--card-bg)",
                    borderColor: "var(--border-primary)",
                    boxShadow: "var(--shadow-primary)",
                }}
            >
                {/* Receipt Header Banner */}
                <div className="relative overflow-hidden border-b p-6 text-center" style={{ borderBottomColor: "var(--border-primary)" }}>
                    <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_50%_0%,var(--primary),transparent_50%)]" />
                    <div className="absolute inset-x-10 top-0 h-[2px] bg-gradient-neon" />
                    <div className="relative">
                        <p className="text-[10px] font-black uppercase tracking-[0.32em] text-primary">PLAYTURF RECEIPT</p>
                        <h2 className="mt-1 font-display text-2xl font-black text-foreground">Booking Confirmed</h2>
                        <p className="mt-2 text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Your Match. Your Turf. Your Victory.</p>
                    </div>
                </div>

                <div className="p-5 sm:p-7">
                    <motion.div
                        initial={{ scale: 0 }}
                        animate={{ scale: 1 }}
                        transition={{ type: "spring", stiffness: 220 }}
                        className="mx-auto grid h-20 w-20 place-items-center rounded-full border transition-all duration-300"
                        style={{
                            borderColor: "var(--border-primary)",
                            backgroundColor: "var(--l-accent-soft)",
                            boxShadow: "var(--l-shadow-glow)"
                        }}
                    >
                        <Check className="h-10 w-10 text-primary" strokeWidth={3} />
                    </motion.div>
                    <div className="mt-5 text-center">
                        <h1 className="font-display text-2xl font-black text-foreground">Transaction Approved</h1>
                        <p className="mt-1.5 text-xs text-muted-foreground font-semibold">Your turf slots have been locked inside Supabase logs.</p>
                    </div>

                    <div
                        className="mt-6 rounded-3xl border p-4 transition-all duration-300"
                        style={{ backgroundColor: "var(--bg-secondary)", borderColor: "var(--border-primary)" }}
                    >
                        <p className="mb-4 text-[9px] font-extrabold uppercase tracking-widest text-primary">Team Roster Showcase</p>
                        <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center">
                            <TeamAvatar team={cricket.teamA} size="lg" className="mx-auto border border-border/40 shadow-sm transition hover:scale-105" />
                            <VsBadge />
                            <TeamAvatar team={cricket.teamB} size="lg" className="mx-auto border border-border/40 shadow-sm transition hover:scale-105" />
                            <p className="truncate text-sm font-black text-foreground font-display">{cricket.teamA?.name}</p>
                            <span />
                            <p className="truncate text-sm font-black text-foreground font-display">{cricket.teamB?.name}</p>
                        </div>
                    </div>

                    <div className="mt-5 grid gap-4 md:grid-cols-2">
                        <ReceiptPanel title="Reservation Details">
                            <ReceiptRow label="Turf Venue" value={booking.turf_name} />
                            <ReceiptRow label="Match Code" value={`${cricket.teamA?.shortName || "A"} VS ${cricket.teamB?.shortName || "B"}`} />
                            <ReceiptRow label="Roster Team" value={cricket.teamA?.name || "Team A"} />
                            <ReceiptRow label="System ID" value={cricket.state.bookingId.slice(0, 10) + "..."} />
                            <ReceiptRow label="Gateway ID" value={booking.payment_id || "TXN-PENDING"} />
                            <ReceiptRow label="Logged Date" value={placedAt.toLocaleDateString()} />
                        </ReceiptPanel>

                        <ReceiptPanel title="Billing Details">
                            <ReceiptRow label="Base Fee" value={`Rs ${total.toLocaleString()}`} />
                            <ReceiptRow label="Platform Charge" value="Rs 20" />
                            <ReceiptRow label="Sports GST (18%)" value={`Rs ${(total * 0.18).toLocaleString()}`} />
                            <ReceiptRow label="Grand Total" value={`Rs ${(total * 1.18 + 20).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`} strong />
                            <ReceiptRow label="Billing method" value={cricket.state.paymentMethod} />
                            <ReceiptRow label="Ledger Status" value="SUCCESS" success />
                        </ReceiptPanel>
                    </div>

                    <div
                        className="mt-6 rounded-3xl border p-4 flex flex-col md:flex-row gap-4 items-center justify-between transition-all duration-300"
                        style={{ backgroundColor: "var(--bg-secondary)", borderColor: "var(--border-primary)" }}
                    >
                        <div className="flex items-center gap-3">
                            <div className="mx-auto grid h-16 w-16 grid-cols-5 gap-1 rounded-xl bg-white p-2.5 shadow-md flex-shrink-0">
                                {Array.from({ length: 25 }).map((_, index) => (
                                    <span key={index} className={`rounded-sm ${index % 2 === 0 || index % 7 === 0 ? "bg-black" : "bg-transparent"}`} />
                                ))}
                            </div>
                            <div>
                                <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-0.5 text-[9px] font-black uppercase tracking-wider text-primary">
                                    <ShieldCheck className="h-3.5 w-3.5" /> Secured Receipt
                                </div>
                                <p className="mt-1.5 text-[11px] text-muted-foreground leading-normal font-semibold">Verified digital signature is securely recorded.</p>
                            </div>
                        </div>
                    </div>

                    <div className="mt-7 hidden grid-cols-2 gap-3 sm:grid">
                        <ReceiptButton onClick={() => downloadReceipt(booking, cricket)} label="Download PDF" icon={Download} primary />
                        <ReceiptButton onClick={() => shareReceipt(booking, cricket)} label="Share Link" icon={Share2} />
                        <button onClick={() => navigate(`/booking/${booking.id}`)} className="pressable rounded-2xl border border-border bg-panel text-foreground text-xs font-black uppercase tracking-wider py-3" style={{ borderColor: "var(--border-primary)", backgroundColor: "var(--card-bg)" }}>View Details</button>
                        <button onClick={() => navigate(`/booking/new/${turf.id}`)} className="pressable rounded-2xl bg-gradient-neon text-primary-foreground text-xs font-black uppercase tracking-wider py-3 shadow-neon border-none">Book New Turf</button>
                    </div>

                    <footer className="mt-7 border-t border-[var(--border-primary)] pt-4 text-center">
                        <p className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider">© 2026 PlayTurf — All Rights Reserved</p>
                        <div className="mt-2 flex flex-wrap justify-center gap-3 text-[9px] text-muted-foreground uppercase font-black tracking-wider">
                            <span>Terms</span>
                            <span>Privacy</span>
                            <span>concierge support</span>
                        </div>
                    </footer>
                </div>
            </div>

            <div
                className="sticky bottom-0 mx-4 mb-4 z-50 rounded-[24px] border bg-panel-3/95 p-3.5 shadow-2xl backdrop-blur-xl sm:hidden"
                style={{ borderColor: "var(--border-primary)" }}
            >
                <div className="mx-auto grid grid-cols-5 gap-2.5">
                    <button onClick={() => downloadReceipt(booking, cricket)} className="pressable rounded-xl bg-gradient-neon text-primary-foreground font-black text-[9px] uppercase py-2.5 shadow-neon">Receipt</button>
                    <button onClick={() => shareReceipt(booking, cricket)} className="pressable rounded-xl border border-border bg-panel text-foreground font-black text-[9px] uppercase py-2.5" style={{ borderColor: "var(--border-primary)" }}>Share</button>
                    <button onClick={() => navigate(`/booking/${booking.id}`)} className="pressable rounded-xl border border-border bg-panel text-foreground font-black text-[9px] uppercase py-2.5" style={{ borderColor: "var(--border-primary)" }}>Details</button>
                    <button onClick={() => navigate("/")} className="pressable rounded-xl border border-border bg-panel text-foreground font-black text-[9px] uppercase py-2.5" style={{ borderColor: "var(--border-primary)" }}>Home</button>
                    <button onClick={() => navigate(`/booking/new/${turf.id}`)} className="pressable rounded-xl bg-gradient-neon text-primary-foreground font-black text-[9px] uppercase py-2.5 shadow-neon">Book New</button>
                </div>
            </div>
        </motion.div>
    );
}
