import { useState } from "react";
import { motion } from "framer-motion";
import { Check, Download, Share2, Copy, MapPin, Calendar, Clock, Timer, CreditCard, Shield, User, Users } from "lucide-react";
import { toast } from "sonner";
import type { Booking } from "@/data/seed";
import type { OpenGame } from "@/types/openGames";

/* ────────────────────────────────────────────────────────────── */

interface JoinGameReceiptProps {
  booking: Booking;
  game: OpenGame;
  playerName: string;
  onClose?: () => void;
}

/* ── Helpers ─────────────────────────────────────────────────── */

const formatTime = (timeStr: string) => {
  const [h, m] = timeStr.split(":").map(Number);
  const ampm = h >= 12 ? "PM" : "AM";
  const hour12 = h % 12 || 12;
  return `${hour12}:${String(m).padStart(2, "0")} ${ampm}`;
};

const formatDate = (dateStr: string) => {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
};

const receiptText = (booking: Booking, game: OpenGame, playerName: string) => {
  const lines = [
    "═══════════════════════════════════════",
    "        PLAY TURF — JOIN RECEIPT",
    "═══════════════════════════════════════",
    "",
    `Joined Game hosted by: ${game.host_name}`,
    "",
    `Receipt ID: ${booking.payment_id || booking.id}`,
    `Booking ID: ${booking.id}`,
    "",
    "────────────── PLAYER ────────────────",
    `Player Name: ${playerName}`,
    "",
    "──────────────── HOST ────────────────",
    `Host Name: ${game.host_name}`,
    "",
    "──────────────── VENUE ───────────────",
    `Turf Name: ${booking.turf_name}`,
    `Sport: ${game.sport}`,
    `Address: ${game.venue}`,
    "",
    "────────────── SCHEDULE ──────────────",
    `Date: ${formatDate(booking.date)}`,
    `Time: ${formatTime(booking.start_time)} — ${formatTime(booking.end_time)}`,
    `Slot: ${Math.round(game.slots_total / 2)}-a-side`,
    `Duration: ${booking.hours} hour(s)`,
    "",
    "────────────── PAYMENT ───────────────",
    `Amount Paid: ₹${booking.amount.toLocaleString("en-IN")}`,
    `Payment Status: ${booking.status}`,
    `Booking Status: ${booking.status}`,
    "",
    `Players Joined: ${game.slots_filled}/${game.slots_total}`,
    `Slots Remaining: ${game.slots_total - game.slots_filled}`,
    "",
    "──────────────────────────────────────",
    "This receipt is digitally generated by Play Turf.",
    "For support, contact: support@playturf.in",
    "═══════════════════════════════════════",
  ];
  return lines.join("\n");
};

/* ── Component ───────────────────────────────────────────────── */

export function JoinGameReceipt({ booking, game, playerName, onClose }: JoinGameReceiptProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(receiptText(booking, game, playerName));
    setCopied(true);
    toast.success("Receipt copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([receiptText(booking, game, playerName)], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Join-Receipt-${booking.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Receipt downloaded");
  };

  const handleShare = async () => {
    const text = receiptText(booking, game, playerName);
    if (navigator.share) {
      await navigator.share({ title: "Play Turf — Join Game Receipt", text });
    } else {
      await navigator.clipboard.writeText(text);
      toast.success("Receipt copied to clipboard");
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-xl overflow-hidden flex flex-col"
      style={{ backgroundColor: "#0a0a0a", border: "1px solid rgba(255,255,255,0.06)" }}
    >
      {/* Header */}
      <div className="relative p-5 text-center" style={{ borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
        <div className="absolute inset-x-10 top-0 h-0.5 bg-emerald-500/50" />
        <div className="flex items-center justify-center gap-2 mb-2">
          <div className="w-8 h-8 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center">
            <Shield className="h-4 w-4 text-emerald-400" />
          </div>
          <span className="text-[10px] font-black uppercase tracking-[0.3em] text-emerald-400/80">Play Turf</span>
        </div>
        <h2 className="font-display text-lg font-black text-white">Join Game Receipt</h2>
        <p className="text-[10px] text-emerald-400/50 mt-1 font-bold">
          Joined Game hosted by: {game.host_name}
        </p>
      </div>

      {/* Body */}
      <div className="p-4 space-y-4">
        {/* Receipt ID */}
        <div className="flex items-center justify-between rounded-lg p-3" style={{ backgroundColor: "#111111" }}>
          <div>
            <p className="text-[9px] text-white/30 uppercase tracking-wider font-bold">Receipt ID</p>
            <p className="text-xs font-mono text-white/60 mt-0.5">{booking.payment_id || booking.id}</p>
          </div>
          <button
            onClick={handleCopy}
            className="p-2 rounded-lg bg-white/5 hover:bg-white/10 transition"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5 text-white/40" />}
          </button>
        </div>

        {/* Player Info */}
        <div className="rounded-lg p-3 space-y-2" style={{ backgroundColor: "#111111" }}>
          <p className="text-[9px] text-emerald-400/60 uppercase tracking-wider font-bold">Player Details</p>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-emerald-500/10 flex items-center justify-center">
              <User className="h-4 w-4 text-emerald-400/60" />
            </div>
            <div>
              <p className="text-sm font-bold text-white">{playerName}</p>
              <p className="text-[10px] text-white/30">Joined Player</p>
            </div>
          </div>
        </div>

        {/* Host Info */}
        <div className="rounded-lg p-3 space-y-2" style={{ backgroundColor: "#111111" }}>
          <p className="text-[9px] text-emerald-400/60 uppercase tracking-wider font-bold">Host Details</p>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-full bg-amber-500/10 flex items-center justify-center">
              <User className="h-4 w-4 text-amber-400/60" />
            </div>
            <div>
              <p className="text-sm font-bold text-white">{game.host_name}</p>
              <p className="text-[10px] text-white/30">Game Host</p>
            </div>
          </div>
        </div>

        {/* Venue Info */}
        <div className="rounded-lg p-3 space-y-2.5" style={{ backgroundColor: "#111111" }}>
          <p className="text-[9px] text-emerald-400/60 uppercase tracking-wider font-bold">Venue Details</p>
          <div className="space-y-2 text-xs">
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><MapPin className="h-3 w-3" /> Turf</span>
              <span className="text-white/80 font-semibold text-right">{booking.turf_name}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><Calendar className="h-3 w-3" /> Sport</span>
              <span className="text-white/80 font-semibold">{game.sport}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><MapPin className="h-3 w-3" /> Address</span>
              <span className="text-white/80 font-semibold text-right max-w-[60%]">{game.venue}</span>
            </div>
          </div>
        </div>

        {/* Schedule */}
        <div className="rounded-lg p-3 space-y-2.5" style={{ backgroundColor: "#111111" }}>
          <p className="text-[9px] text-emerald-400/60 uppercase tracking-wider font-bold">Schedule</p>
          <div className="space-y-2 text-xs">
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><Calendar className="h-3 w-3" /> Date</span>
              <span className="text-white/80 font-semibold">{formatDate(booking.date)}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><Clock className="h-3 w-3" /> Time</span>
              <span className="text-white/80 font-semibold">{formatTime(booking.start_time)} — {formatTime(booking.end_time)}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><Timer className="h-3 w-3" /> Slot</span>
              <span className="text-white/80 font-semibold">{Math.round(game.slots_total / 2)}-a-side</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><Timer className="h-3 w-3" /> Duration</span>
              <span className="text-white/80 font-semibold">{booking.hours} hour(s)</span>
            </div>
          </div>
        </div>

        {/* Payment */}
        <div className="rounded-lg p-3 space-y-2.5" style={{ backgroundColor: "#111111" }}>
          <p className="text-[9px] text-emerald-400/60 uppercase tracking-wider font-bold">Payment</p>
          <div className="space-y-2 text-xs">
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><CreditCard className="h-3 w-3" /> Amount Paid</span>
              <span className="text-emerald-400 font-black text-sm">₹{booking.amount.toLocaleString("en-IN")}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><Shield className="h-3 w-3" /> Payment Status</span>
              <span className="text-emerald-400 font-semibold">{booking.status}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-white/40 flex items-center gap-1.5"><Shield className="h-3 w-3" /> Booking Status</span>
              <span className="text-emerald-400 font-semibold">{booking.status}</span>
            </div>
          </div>
        </div>

        {/* Player Count */}
        <div className="rounded-lg p-3" style={{ backgroundColor: "#111111" }}>
          <div className="flex items-center justify-between text-xs">
            <span className="text-white/40 flex items-center gap-1.5"><Users className="h-3 w-3" /> Players Joined</span>
            <span className="text-emerald-400 font-semibold">{game.slots_filled} / {game.slots_total}</span>
          </div>
          <div className="w-full h-1.5 rounded-full mt-2" style={{ backgroundColor: "#1a1a1a" }}>
            <div
              className="h-full rounded-full bg-emerald-500/60"
              style={{ width: `${(game.slots_filled / game.slots_total) * 100}%` }}
            />
          </div>
          <p className="text-[10px] text-white/20 mt-1 text-right">
            {game.slots_total - game.slots_filled} spots remaining
          </p>
        </div>

        {/* Actions */}
        <div className="grid grid-cols-3 gap-2">
          <button
            onClick={handleDownload}
            className="py-2.5 rounded-lg font-bold text-[10px] uppercase tracking-wider flex items-center justify-center gap-1.5 transition"
            style={{ backgroundColor: "#111111", color: "rgba(255,255,255,0.6)", border: "1px solid rgba(255,255,255,0.08)" }}
          >
            <Download className="h-3.5 w-3.5" /> Download
          </button>
          <button
            onClick={handleShare}
            className="py-2.5 rounded-lg font-bold text-[10px] uppercase tracking-wider flex items-center justify-center gap-1.5 transition"
            style={{ backgroundColor: "#111111", color: "rgba(255,255,255,0.6)", border: "1px solid rgba(255,255,255,0.08)" }}
          >
            <Share2 className="h-3.5 w-3.5" /> Share
          </button>
          {onClose && (
            <button
              onClick={onClose}
              className="py-2.5 rounded-lg font-bold text-[10px] uppercase tracking-wider flex items-center justify-center gap-1.5 transition"
              style={{ backgroundColor: "rgba(34,197,94,0.15)", color: "#22c55e", border: "1px solid rgba(34,197,94,0.2)" }}
            >
              Done
            </button>
          )}
        </div>

        {/* Footer */}
        <div className="text-center pt-2" style={{ borderTop: "1px solid rgba(255,255,255,0.04)" }}>
          <p className="text-[9px] text-white/20 uppercase tracking-wider font-bold">© 2026 Play Turf — All Rights Reserved</p>
          <div className="flex justify-center gap-3 mt-1">
            <span className="text-[8px] text-white/15">Terms</span>
            <span className="text-[8px] text-white/15">Privacy</span>
            <span className="text-[8px] text-white/15">Support</span>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
