import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.1", fontWeight: "700" }],
        h2: ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        h3: ["22px", { lineHeight: "1.3", fontWeight: "700" }],
        h4: ["18px", { lineHeight: "1.4", fontWeight: "700" }],
        bodySmall: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "hero-title": ["32px", { lineHeight: "40px" }],
        "screen-title": ["28px", { lineHeight: "36px" }],
        "section-title": ["24px", { lineHeight: "32px" }],
        "card-title": ["20px", { lineHeight: "28px" }],
        "subtitle": ["18px", { lineHeight: "26px" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
        "secondary-text": ["14px", { lineHeight: "22px" }],
        "small-label": ["12px", { lineHeight: "18px" }],
        "button-text": ["16px", { lineHeight: "20px" }],
        "nav-text": ["12px", { lineHeight: "16px" }],
      },
      spacing: {
        xs: "var(--spacing-xs, 0.25rem)",
        sm: "var(--spacing-sm, 0.5rem)",
        md: "var(--spacing-md, 1rem)",
        lg: "var(--spacing-lg, 1.5rem)",
        xl: "var(--spacing-xl, 2rem)",
        "2xl": "var(--spacing-2xl, 3rem)",
        slidePadding: "var(--spacing-slide-padding, 1.5rem)",
        elementGap: "var(--spacing-element-gap, 1rem)",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        surface: "hsl(var(--surface))",
        textMuted: "hsl(var(--text-muted))",
        danger: "hsl(var(--danger))",
        warning: "hsl(var(--warning))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: "hsl(var(--success))",
        panel: {
          DEFAULT: "hsl(var(--panel))",
          2: "hsl(var(--panel-2))",
          3: "hsl(var(--panel-3))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "var(--radius-sm, 0.25rem)",
        card: "var(--radius-card, 0.75rem)",
        input: "var(--radius-input, 0.5rem)",
        "2xl": "1.25rem",
        "3xl": "1.75rem",
      },
      boxShadow: {
        neon: "var(--shadow-neon)",
        "neon-lg": "var(--shadow-neon-lg)",
        card: "var(--shadow-card)",
      },
      backgroundImage: {
        "gradient-neon": "var(--gradient-neon)",
        "gradient-overlay": "var(--gradient-overlay)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(10px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { opacity: "0", transform: "scale(0.96)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 hsl(73 95% 51% / 0.55), 0 0 22px hsl(73 95% 51% / 0.5)" },
          "50%": { boxShadow: "0 0 0 14px hsl(73 95% 51% / 0), 0 0 32px hsl(73 95% 51% / 0.7)" },
        },
        "shimmer": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "float": { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-4px)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s ease-out",
        "scale-in": "scale-in 0.25s ease-out",
        "pulse-glow": "pulse-glow 2.2s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
