import { CheckCircle2, Copy, Download, Home, RotateCcw, Share2, ShieldCheck, Trophy } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { ReactNode } from "react";
import { motion } from "framer-motion";
import { toast } from "sonner";
import receiptAssets from "@/assets/play-turf-receipt-assets.webp";

const receipt = {
  bookingId: "PT-2026-847392",
  transactionId: "TXN984738292",
  matchType: "Match Winner",
  selectedTeam: "Thunder Strikers",
  teamA: "Thunder Strikers",
  teamB: "Royal Blazers",
  betAmount: 1000,
  platformFee: 20,
  gst: 3.6,
  paymentMethod: "UPI",
  status: "SUCCESS",
  dateTime: "02 May 2026 - 08:45 PM",
};

const totalPaid = receipt.betAmount + receipt.platformFee + receipt.gst;

export default function Receipt() {
  const receiptText = [
    "PLAY_TURF Payment Receipt",
    "Your Match. Your Turf. Your Victory.",
    `Booking ID: ${receipt.bookingId}`,
    `Transaction ID: ${receipt.transactionId}`,
    `Match: ${receipt.teamA} VS ${receipt.teamB}`,
    `Selected Team: ${receipt.selectedTeam}`,
    `Total Paid: Rs ${totalPaid.toFixed(2)}`,
    `Payment Method: ${receipt.paymentMethod}`,
    `Payment Status: ${receipt.status}`,
    "This receipt is digitally generated by PLAY_TURF.",
  ].join("\n");

  const copyTxn = async () => {
    await navigator.clipboard.writeText(receipt.transactionId);
    toast.success("Transaction ID copied");
  };

  const download = () => {
    const blob = new Blob([receiptText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${receipt.bookingId}-receipt.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
    toast.success("Receipt downloaded");
  };

  const share = async () => {
    if (navigator.share) await navigator.share({ title: "PLAY_TURF Receipt", text: receiptText });
    else {
      await navigator.clipboard.writeText(receiptText);
      toast.success("Receipt copied");
    }
  };

  return (
    <main className="relative min-h-screen overflow-hidden bg-[#050814] text-[#F5F7FA] lg:h-screen">
      <div className="absolute inset-0 opacity-35" style={{ backgroundImage: `url(${receiptAssets})`, backgroundSize: "cover", backgroundPosition: "center" }} />
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_0%,rgba(57,255,20,.22),transparent_30%),radial-gradient(circle_at_80%_10%,rgba(0,217,255,.24),transparent_34%),linear-gradient(180deg,rgba(11,16,32,.78),#050814_58%)]" />

      <div className="pointer-events-none absolute inset-0">
        {Array.from({ length: 26 }).map((_, index) => (
          <span
            key={index}
            className="absolute h-1 w-1 animate-float rounded-full bg-[#00D9FF] shadow-[0_0_16px_rgba(0,217,255,.9)]"
            style={{ left: `${(index * 17) % 100}%`, top: `${8 + ((index * 29) % 84)}%`, animationDelay: `${index * 0.12}s` }}
          />
        ))}
        {Array.from({ length: 18 }).map((_, index) => (
          <span
            key={`confetti-${index}`}
            className="animate-confetti absolute h-2 w-2 rounded-full"
            style={{ left: `${(index * 31) % 100}%`, background: index % 2 ? "#39FF14" : "#00D9FF", animationDelay: `${index * 0.1}s` }}
          />
        ))}
      </div>

      <motion.section
        initial={{ opacity: 0, y: 18 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45 }}
        className="relative z-10 mx-auto flex w-full max-w-6xl items-center px-3 py-4 pb-28 sm:px-5"
      >
        <div className="grid w-full gap-3 rounded-[2rem] border border-cyan-300/20 bg-[#0B1020]/82 p-3 shadow-[0_0_100px_rgba(0,217,255,.18)] backdrop-blur-2xl sm:p-5 lg:max-h-[calc(100vh-2rem)] lg:grid-cols-[.78fr_1.22fr] lg:overflow-hidden">
          <HeaderStatus />

          <div className="grid min-h-0 gap-3 lg:grid-rows-[auto_1fr_auto]">
            <MatchShowcase />

            <div className="grid min-h-0 gap-3 lg:grid-cols-[1fr_.78fr]">
              <DetailsCard copyTxn={copyTxn} />
              <SecurityCard />
            </div>

            <div className="hidden grid-cols-4 gap-2 lg:grid">
              <ActionButton label="Download Receipt" icon={Download} onClick={download} primary />
              <ActionButton label="Share Receipt" icon={Share2} onClick={share} />
              <ActionButton label="Book Another Match" icon={RotateCcw} onClick={() => toast.success("Ready for another match")} primary />
              <ActionButton label="Back to Home" icon={Home} onClick={() => (window.location.href = "/")} />
            </div>
          </div>

          <footer className="border-t border-white/10 pt-3 text-center lg:col-span-2">
            <div className="flex flex-wrap justify-center gap-3 text-[11px] text-cyan-100/65">
              <span>Terms & Conditions</span>
              <span>Privacy Policy</span>
              <span>Responsible Gaming</span>
              <span>Support</span>
            </div>
            <p className="mt-2 text-[11px] text-white/45">© 2026 PLAY_TURF — All Rights Reserved</p>
          </footer>
        </div>
      </motion.section>

      <div className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-4 gap-2 border-t border-white/10 bg-[#0B1020]/92 p-3 backdrop-blur-xl lg:hidden">
        <ActionButton label="Download" icon={Download} onClick={download} primary compact />
        <ActionButton label="Share" icon={Share2} onClick={share} compact />
        <ActionButton label="Book Again" icon={RotateCcw} onClick={() => toast.success("Ready for another match")} primary compact />
        <ActionButton label="Home" icon={Home} onClick={() => (window.location.href = "/")} compact />
      </div>
    </main>
  );
}

function HeaderStatus() {
  return (
    <div className="relative overflow-hidden rounded-[1.5rem] border border-white/10 bg-white/[0.06] p-5 text-center lg:flex lg:flex-col lg:justify-between">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(57,255,20,.2),transparent_35%),linear-gradient(160deg,rgba(0,217,255,.12),transparent)]" />
      <div className="relative">
        <div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-[#39FF14]/30 bg-[#39FF14]/10 shadow-[0_0_34px_rgba(57,255,20,.35)]">
          <Trophy className="h-7 w-7 text-[#39FF14]" />
        </div>
        <h1 className="mt-3 font-display text-3xl font-black tracking-tight">PLAY_TURF</h1>
        <p className="mt-1 text-xs font-semibold text-white/60">Your Match. Your Turf. Your Victory.</p>
      </div>

      <div className="relative mt-6">
        <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} transition={{ type: "spring", stiffness: 220 }} className="mx-auto grid h-24 w-24 place-items-center rounded-full border border-[#39FF14]/40 bg-[#39FF14]/15 shadow-[0_0_55px_rgba(57,255,20,.46)]">
          <CheckCircle2 className="h-14 w-14 text-[#39FF14]" />
        </motion.div>
        <h2 className="mt-4 text-2xl font-black">PAYMENT SUCCESSFUL</h2>
        <p className="mt-2 text-sm text-white/62">Your booking has been confirmed successfully.</p>
      </div>
    </div>
  );
}

function MatchShowcase() {
  return (
    <div className="relative overflow-hidden rounded-[1.5rem] border border-[#00D9FF]/20 bg-white/[0.06] p-4">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(0,217,255,.2),transparent_34%)]" />
      <div className="relative grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center">
        <TeamLogo name={receipt.teamA} tone="green" />
        <div className="grid h-20 w-20 place-items-center rounded-full border border-cyan-300/50 bg-black/70 shadow-[0_0_45px_rgba(0,217,255,.48)]">
          <span className="text-2xl font-black text-white drop-shadow-[0_0_16px_rgba(0,217,255,.9)]">VS</span>
        </div>
        <TeamLogo name={receipt.teamB} tone="blue" />
      </div>
    </div>
  );
}

function TeamLogo({ name, tone }: { name: string; tone: "green" | "blue" }) {
  const isGreen = tone === "green";
  const initials = name.split(" ").map((part) => part[0]).join("").toUpperCase();
  const glowColor = isGreen ? "#39FF14" : "#00D9FF";
  const secondaryColor = isGreen ? "#16a34a" : "#2563eb";

  return (
    <div className="group flex flex-col items-center min-w-0">
      <div className="relative h-20 w-20 transition duration-300 group-hover:scale-110">
        {/* Glow Ring */}
        <div 
          className="absolute inset-0 rounded-full blur-md opacity-35 transition-opacity group-hover:opacity-60"
          style={{ background: `radial-gradient(circle, ${glowColor} 0%, transparent 70%)` }}
        />
        {/* SVG Shield/Emblem */}
        <svg viewBox="0 0 100 100" className="relative h-full w-full drop-shadow-[0_4px_10px_rgba(0,0,0,0.5)]">
          <defs>
            <linearGradient id={`grad-${tone}`} x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" stopColor={glowColor} />
              <stop offset="100%" stopColor={secondaryColor} />
            </linearGradient>
            <radialGradient id={`glow-internal-${tone}`}>
              <stop offset="0%" stopColor={glowColor} stopOpacity="0.15" />
              <stop offset="100%" stopColor="#000000" stopOpacity="0.8" />
            </radialGradient>
          </defs>
          {/* Main Shield Path */}
          <path 
            d="M 50 6 L 82 24 C 82 60, 50 88, 50 88 C 50 88, 18 60, 18 24 Z" 
            fill={`url(#glow-internal-${tone})`}
            stroke={`url(#grad-${tone})`} 
            strokeWidth="3"
            strokeLinejoin="round"
          />
          {/* Internal Accent Lines */}
          <path 
            d="M 50 12 L 77 28 C 77 56, 50 80, 50 80 C 50 80, 23 56, 23 28 Z" 
            fill="none" 
            stroke={glowColor} 
            strokeWidth="1" 
            strokeDasharray="2 2"
            opacity="0.4"
          />
          {/* Team Initials */}
          <text 
            x="50" 
            y="57" 
            fill="#FFFFFF" 
            fontSize="20" 
            fontWeight="900" 
            fontFamily="system-ui, -apple-system, sans-serif"
            textAnchor="middle"
            letterSpacing="0.5"
            className="drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]"
          >
            {initials}
          </text>
        </svg>
      </div>
      <p className="mt-2.5 truncate text-xs font-black tracking-wide text-white/85 group-hover:text-white transition-colors">{name}</p>
    </div>
  );
}

function DetailsCard({ copyTxn }: { copyTxn: () => void }) {
  return (
    <div className="rounded-[1.5rem] border border-white/10 bg-black/25 p-4">
      <div className="mb-3 flex items-center justify-between">
        <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-100/70">Payment Details</p>
        <span className="rounded-full border border-[#39FF14]/30 bg-[#39FF14]/10 px-3 py-1 text-[11px] font-black text-[#39FF14]">SUCCESS</span>
      </div>
      <div className="space-y-2">
        <ReceiptRow label="Booking ID" value={receipt.bookingId} />
        <ReceiptRow label="Transaction ID" value={receipt.transactionId} action={<button onClick={copyTxn} className="text-[#00D9FF] hover:text-white transition-colors"><Copy className="h-4 w-4" /></button>} />
        <ReceiptRow label="Match Type" value={receipt.matchType} />
        <ReceiptRow label="Selected Team" value={receipt.selectedTeam} />
        <ReceiptRow label="Bet Amount" value={`Rs ${receipt.betAmount.toLocaleString("en-IN")}`} />
        <ReceiptRow label="Platform Fee" value={`Rs ${receipt.platformFee}`} />
        <ReceiptRow label="GST" value={`Rs ${receipt.gst.toFixed(2)}`} />
        <ReceiptRow label="Total Paid" value={`Rs ${totalPaid.toFixed(2)}`} strong />
        <ReceiptRow label="Payment Method" value={receipt.paymentMethod} />
        <ReceiptRow label="Date & Time" value={receipt.dateTime} />
      </div>
    </div>
  );
}

function SecurityCard() {
  return (
    <div className="rounded-[1.5rem] border border-[#39FF14]/15 bg-[#39FF14]/[0.02] p-4 flex flex-col justify-between">
      <div>
        <p className="text-xs font-black uppercase tracking-[0.22em] text-lime-400/80">Digital Signature</p>
        
        {/* Futuristic Barcode with Scanning Line */}
        <div className="relative mx-auto mt-4 flex h-20 w-44 flex-col items-center justify-center rounded-xl bg-white/5 p-3 backdrop-blur-md border border-white/5 overflow-hidden group">
          {/* Scan line animation */}
          <div className="absolute inset-x-0 h-[1.5px] bg-gradient-to-r from-transparent via-[#39FF14] to-transparent animate-[pulse_1.5s_infinite] shadow-[0_0_8px_#39FF14] z-10" />
          
          <svg viewBox="0 0 100 40" className="h-full w-full opacity-70 group-hover:opacity-90 transition-opacity">
            <rect x="5" y="5" width="2" height="30" fill="#39FF14" />
            <rect x="9" y="5" width="4" height="30" fill="#39FF14" />
            <rect x="15" y="5" width="1" height="30" fill="#39FF14" />
            <rect x="18" y="5" width="3" height="30" fill="#39FF14" />
            <rect x="23" y="5" width="1" height="30" fill="#39FF14" />
            <rect x="26" y="5" width="5" height="30" fill="#39FF14" />
            <rect x="33" y="5" width="2" height="30" fill="#39FF14" />
            <rect x="37" y="5" width="1" height="30" fill="#39FF14" />
            <rect x="40" y="5" width="4" height="30" fill="#39FF14" />
            <rect x="46" y="5" width="2" height="30" fill="#39FF14" />
            <rect x="50" y="5" width="1" height="30" fill="#39FF14" />
            <rect x="53" y="5" width="3" height="30" fill="#39FF14" />
            <rect x="58" y="5" width="5" height="30" fill="#39FF14" />
            <rect x="65" y="5" width="1" height="30" fill="#39FF14" />
            <rect x="68" y="5" width="2" height="30" fill="#39FF14" />
            <rect x="72" y="5" width="4" height="30" fill="#39FF14" />
            <rect x="78" y="5" width="1" height="30" fill="#39FF14" />
            <rect x="81" y="5" width="3" height="30" fill="#39FF14" />
            <rect x="86" y="5" width="2" height="30" fill="#39FF14" />
            <rect x="90" y="5" width="5" height="30" fill="#39FF14" />
          </svg>
          <span className="text-[8px] font-mono text-white/50 tracking-widest mt-1">VERIFIED SECURE</span>
        </div>
      </div>
      
      <div className="mt-4 rounded-2xl border border-white/5 bg-black/30 p-3">
        <div className="inline-flex items-center gap-1.5 rounded-full border border-[#39FF14]/25 bg-[#39FF14]/10 px-2.5 py-0.5 text-[10px] font-bold text-lime-400">
          <ShieldCheck className="h-3.5 w-3.5" /> SECURE CHECKOUT
        </div>
        <p className="mt-2 text-xs font-semibold text-white/70">Receipt Authenticated</p>
        <p className="mt-0.5 text-[10px] text-white/40">Secured transaction token verified by PLAY_TURF.</p>
      </div>
    </div>
  );
}

function ReceiptRow({ label, value, strong, action }: { label: string; value: string; strong?: boolean; action?: ReactNode }) {
  return (
    <div className="flex items-center justify-between gap-3 border-b border-white/5 pb-2 text-sm last:border-0 last:pb-0">
      <span className="text-white/48">{label}</span>
      <span className={`ml-auto text-right font-semibold ${strong ? "text-[#39FF14]" : "text-white"}`}>{value}</span>
      {action}
    </div>
  );
}

function ActionButton({ label, icon: Icon, onClick, primary, compact }: { label: string; icon: LucideIcon; onClick: () => void; primary?: boolean; compact?: boolean }) {
  return (
    <button
      onClick={onClick}
      className={`pressable inline-flex items-center justify-center gap-2 rounded-2xl font-black transition ${compact ? "min-h-12 px-2 text-[11px]" : "min-h-12 px-3 text-xs"
        } ${primary ? "bg-gradient-to-r from-[#39FF14] to-[#00D9FF] text-black shadow-[0_0_28px_rgba(57,255,20,.34)]" : "border border-white/10 bg-white/10 text-white hover:border-cyan-300/40"}`}
    >
      <Icon className="h-4 w-4" />
      {label}
    </button>
  );
}
